# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='name',
            new_name='name_country',
        ),
        migrations.AlterUniqueTogether(
            name='club',
            unique_together=set([('name',)]),
        ),
    ]
