# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20160411_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulr_video', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.TextField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name_country']},
        ),
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='stadium',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='service.Country'),
        ),
        migrations.AlterUniqueTogether(
            name='country',
            unique_together=set([('name_country', 'short_name')]),
        ),
        migrations.AddField(
            model_name='tournaments',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Country'),
        ),
        migrations.AddField(
            model_name='match',
            name='guest_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_club', to='service.Club'),
        ),
        migrations.AddField(
            model_name='match',
            name='host_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_club', to='service.Club'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournaments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='service.Tournaments'),
        ),
    ]
