# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20160416_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='tournaments',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='match',
            name='ulr_video',
        ),
    ]
