# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_matchdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='thumnail',
            field=models.URLField(default=''),
        ),
    ]
