# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_match_thumnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(max_length=200, null=True, upload_to=''),
        ),
    ]
