# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20160501_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.TextField(null=True),
        ),
    ]
